name: pluto_inside
description: The package for Pluto package series. Developing packages that make it easy to develop services like admin pages or CMS with Flutter.
version: 0.1.1
homepage: https://bosskmk.github.io
repository: https://github.com/bosskmk/pluto_inside

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

assets:
  - assets/icons/checkBoxFilled.png
  - assets/icons/checkBoxEmpty.png
  - assets/icons/radioEmpty.png